apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: udemy-microservices-nodejs-react
build:
  local:
    push: false
  artifacts:
    - image: aneeqtariq143/udemy-microservices-nodejs-react-auth-service
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: aneeqtariq143/udemy-microservices-nodejs-react-client-service
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          # Sync all the ts and tsx files in the src directory
          - src: '**/*.{ts,tsx}'
            dest: .
    - image: aneeqtariq143/udemy-microservices-nodejs-react-tickets-service
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: aneeqtariq143/udemy-microservices-nodejs-react-orders-service
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
manifests:
  rawYaml:
    - infra/k8s/*
