import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/app/ui/Header";
import buildAxiosClient from "@/app/helpers/build-axios-client";

const inter = Inter({subsets: ["latin"]});

export interface CurrentUserInterface {
    id: string;
    email: string;
    iam: string;
}

async function getAuth(): Promise<CurrentUserInterface | undefined> {
    const axiosClient = buildAxiosClient();

    try {
        const response = await axiosClient.get("/api/users/currentuser");
        return response.data.currentUser;
    } catch (error) {
        console.error(error);
        return undefined // Handle error or no auth state
    }
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    const auth = await getAuth();

    return (
        <html lang="en">
        <body className={inter.className}>
        <Header currentUser={auth}/>
        {children}
        </body>
        </html>
    );
}
