# This file is used to create a deployment for the auth service
apiVersion: apps/v1
# Kind is the type of resource we are creating
kind: Deployment
# Metadata is data about the resource
metadata:
  # Name is the name of the resource
  name: auth-depl
# Spec is the configuration of the resource
spec:
  # Replicas is the number of pods we want to run
  replicas: 1
  # Selector is used to select which pods this deployment is going to manage
  selector:
    matchLabels:
      # app: auth is the label of the pods
      app: auth
  # Template is the configuration of the pods
  template:
    metadata:
      # Labels is the labels of the pods
      labels:
        # app: auth is the label of the pods
        app: auth
      # Spec is the configuration of the containers
    spec:
      # Init containers run before the main application containers
      initContainers:
        # Init container to wait for MongoDB to be ready
        - name: auth-wait-for-mongo
          image: appropriate/curl  # Lightweight image with networking tools
          command:
            - sh
            - -c
            - |
              echo "Waiting for MongoDB..."
              until nc -z auth-mongo-srv 27017; do
                echo "MongoDB is unavailable - sleeping"
                sleep 5
              done
              echo "MongoDB is up - proceeding"
      containers:
        # - name is the name of the container
        - name: auth
          # Image is the image of the container
          image: aneeqtariq143/udemy-microservices-nodejs-react-auth-service
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
# apiVersion is the version of the API
apiVersion: v1
# Kind is the type of resource we are creating
kind: Service
# Metadata is data about the resource
metadata:
  # Name is the name of the resource
  name: auth-srv
# Spec is the configuration of the resource
spec:
  # Selector is used to select which pods this service is going to route traffic to
  selector:
    # app: auth is the label of the pods
    app: auth
  # Ports is the list of ports
  ports:
    - name: auth
      # - protocol is the protocol of the port
      protocol: TCP
      # port is the port of the service
      port: 3000
      # targetPort is the port of the pods
      targetPort: 3000