name: tests-ticket
   
on:
  pull_request:
    # Run tests on pull requests
    paths:
      # Only run tests on changes to the tickets directory
      - 'tickets/**'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd tickets && npm install && npm run test:ci
