name: tests-auth

on:
  pull_request:
    # Run tests on pull requests
    paths:
    # Only run tests on changes to the auth directory
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd auth && npm install && npm run test:ci
