name: tests-order
   
on:
  pull_request:
    # Run tests on pull requests
    paths:
      # Only run tests on changes to the orders directory
      - 'orders/**'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cd orders && npm install && npm run test:ci
